### ISSUE TITLE
[BUG] Stuck in Toggled Staffchat

### ISSUE THREAD

**Issue by nicholasveronico** [HyperaOfficial/UltraStaffChat#1]
**Describe the bug**
I was on UltraStaffchat 4.0.1 and upgraded to the new 5.0 version. I deleted the old config as suggested and had the proxy restarted. I logged on and I was stuck in toggled staff chat with no way of exiting. I tried /sctoggle, which prompted a message that I toggled staff chat on. I still tried speaking, as I thought maybe the toggle messages were inverted, but I was still in staff chat. I also tried disabling the staff chat toggle in the config and reloaded, but I was still stuck in staff chat.

**To Reproduce**
Install the new version of USC, delete the old config, and log on with the staffchat.talk, read, etc. permissions and it resulted in being stuck in staff chat.

**Expected behavior**
I expected not to be in staff chat when logging on to the server and when doing /sctoggle, and was prompted with the message that staff chat was enabled, then doing it again to get the message that it was disabled, it should have disabled staff chat for my player.

**Screenshots**
![2021-05-04_00 16 11](https://user-images.githubusercontent.com/80995156/117019236-3d2ea780-acc3-11eb-86b4-8f37b8eae680.png)

**Environment**
 - OS: Ubuntu 20.04 (5.4.0-72-generic)
 - Proxy Version: Waterfall (git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:95c9b6c:411)
 - UltraStaffChat Version: 5.0.0

**Advanced Debug Log**
https://paste.hypera.dev/apakadeheb.txt

**Additional context**
I ended up downgrading back to 4.0.1 for the time being because our server has over 100 players online and I cannot keep restarting to fix issues.

**Comment by SLLCoding** [comment]
Fixed by commit ee01daa, attached is a jar you can use until 5.0.1 is released.
[UltraStaffChat-5.0.1-DEV.zip](https://github.com/HyperaOfficial/UltraStaffChat/files/6422153/UltraStaffChat-5.0.1-DEV.zip)

**Comment by SLLCoding** [comment]
Let's try that one again, here is another jar:
[UltraStaffChat-5.0.1-DEV.zip](https://github.com/HyperaOfficial/UltraStaffChat/files/6422441/UltraStaffChat-5.0.1-DEV.zip)
