### ISSUE TITLE
[BUG] Message don't send in discord

### ISSUE THREAD

**Issue by iBuseWinner** [HyperaOfficial/UltraStaffChat#12]
**Describe the bug**
If we use " in message (`/sc some random" text`) and Discord staffchat message is enabled then we get error in console.

**To Reproduce**
Write random message in staffchat with " in it

**Expected behavior**
Message need to be sent in Discord.

**Screenshots**
java.io.IOException: Server returned HTTP response code: 400 for URL: https://discord.com/api/webhooks/878749975620747314/xxxxx

**Environment**
 - OS: Debian
 - Proxy Version: BungeeCord 1.16
 - UltraStaffChat Version: 5.1.1

**Advanced Debug Log**
https://paste.hypera.dev/ijikenutomenobifeqepihidajikisac.txt

**Additional context**
Also if we write <@discord id (user/role)> it will be mentioned. What if someone spam with it? Can you replace @ to another symbol before send message?
If we use discord style message symbols (\*, _, ~) then in discord we will se §l and etc. Can you replace all these symbols with \\* ? E.g.:
Staff1: /sc \|\|hi\|\|, \*\*disc\*\*\_ord\_ -> (Discord) Staff1: ||hi||, **disc**_ord_

And, please, remove &\<color\> from discord messages.

**Comment by SLLCoding** [comment]
We'll look into it, I'd regenerate your webhook if you haven't already, those are supposed to be kept secret.
