### ISSUE TITLE
[BUG] Empty messages

### ISSUE THREAD

**Issue by iBuseWinner** [HyperaOfficial/UltraStaffChat#13]
**Describe the bug**
We can send empty messages in staffchat/discord

**To Reproduce**
Full empty message: enable staffchat-prefix in config. For me it's "\\"".
Write in chat this symbol and send it. We sent invisible message in chat & discord.

Empty message in chat and color code in discord:
Write /sc &l or another color code and send this command. In chat we will se invisible message and in discord we will see this color code.

**Expected behavior**
Don't allow players to send empty messages.

**Screenshots**
1)
![image](https://user-images.githubusercontent.com/44753872/130683402-726044f9-9737-4072-823b-ac54bdc32cee.png)

2)
![image](https://user-images.githubusercontent.com/44753872/130683464-21d82010-ce4f-4a92-9ebb-410cc2606868.png)

**Environment && Advanced Debug Log**
Same as in
https://github.com/HyperaOfficial/UltraStaffChat/issues/12

**Comment by SLLCoding** [comment]
To a certain extent, blank messages are expected behaviour. Although, the chat colours showing in Discord should not happen, thanks for reporting!
