### ISSUE TITLE
Velocity Support

### ISSUE THREAD

**Issue by e-splat** [HyperaOfficial/UltraStaffChat#73]
**Is your feature request related to a problem? Please describe.**
It is not compatible with Velocity, so i need to use it with Snap

**Describe the solution you'd like**
I will like a Velocity version of this plugin, nowdays it is increasing in servers

**Comment by SLLCoding** [comment]
Velocity support is an [UltraStaffChatPro](https://www.spigotmc.org/resources/ultrastaffchatpro.80461/) feature.
